-- AlterTable
ALTER TABLE "Address" ALTER COLUMN "lat" SET DATA TYPE DECIMAL(14,11),
ALTER COLUMN "lng" SET DATA TYPE DECIMAL(14,11);

-- AlterTable
ALTER TABLE "Carrier" ALTER COLUMN "lat" SET DATA TYPE DECIMAL(14,11),
ALTER COLUMN "lng" SET DATA TYPE DECIMAL(14,11);

-- AlterTable
ALTER TABLE "Request" ALTER COLUMN "organizationLat" SET DATA TYPE DECIMAL(14,11),
ALTER COLUMN "organizationLng" SET DATA TYPE DECIMAL(14,11);
